apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq-pod
  template:
    metadata:
      labels:
        run: rabbitmq-pod
    spec:
      containers:
        - name: rabbitmq-ctn
          image: rabbitmq
          ports:
            - name: rabbitmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rabbit_mq_data
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rabbit_mq_data

