apiVersion: v1
kind: Service
metadata:
  # must is the same: https://github.com/duongdx-kma/vprofile-project/blob/containers/src/main/resources/application.properties#L9C23-L9C40
  name: java-memcached-01
  labels:
    app: java-app
spec:
  selector:
    run: memcahed-pod
  type: ClusterIP
  ports:
    - port: 11211
      protocol: TCP
      targetPort: memcached-port
